/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 30/09/2020 12:06:50
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_SYSCLKFreq_VALUE                     80000000
#define MX_HCLKFreq_Value                       80000000
#define MX_FCLKCortexFreq_Value                 80000000
#define MX_CortexFreq_Value                     80000000
#define MX_AHBFreq_Value                        80000000
#define MX_APB1Freq_Value                       80000000
#define MX_APB2Freq_Value                       80000000
#define MX_APB1TimFreq_Value                    80000000
#define MX_APB2TimFreq_Value                    80000000
#define MX_PWRFreq_Value                        80000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        48000000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    80000000

/*-------------------------------- FMC        --------------------------------*/

#define MX_FMC                                  1

/* GPIO Configuration */

/* Pin PE11 */
#define MX_FMC_D8_DA8_Pin                       PE11
#define MX_FMC_D8_DA8_GPIOx                     GPIOE
#define MX_FMC_D8_DA8_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D8_DA8_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D8_DA8_GPIO_Pin                  GPIO_PIN_11
#define MX_FMC_D8_DA8_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D8_DA8_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PF0 */
#define MX_FMC_A0_Pin                           PF0
#define MX_FMC_A0_GPIOx                         GPIOF
#define MX_FMC_A0_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A0_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A0_GPIO_Pin                      GPIO_PIN_0
#define MX_FMC_A0_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A0_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD7 */
#define MX_FMC_NE1_Pin                          PD7
#define MX_FMC_NE1_GPIOx                        GPIOD
#define MX_FMC_NE1_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_NE1_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NE1_GPIO_Pin                     GPIO_PIN_7
#define MX_FMC_NE1_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NE1_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PF1 */
#define MX_FMC_A1_Pin                           PF1
#define MX_FMC_A1_GPIOx                         GPIOF
#define MX_FMC_A1_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A1_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A1_GPIO_Pin                      GPIO_PIN_1
#define MX_FMC_A1_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A1_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD1 */
#define MX_FMC_D3_DA3_Pin                       PD1
#define MX_FMC_D3_DA3_GPIOx                     GPIOD
#define MX_FMC_D3_DA3_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D3_DA3_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D3_DA3_GPIO_Pin                  GPIO_PIN_1
#define MX_FMC_D3_DA3_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D3_DA3_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PF2 */
#define MX_FMC_A2_Pin                           PF2
#define MX_FMC_A2_GPIOx                         GPIOF
#define MX_FMC_A2_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A2_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A2_GPIO_Pin                      GPIO_PIN_2
#define MX_FMC_A2_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A2_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PF3 */
#define MX_FMC_A3_Pin                           PF3
#define MX_FMC_A3_GPIOx                         GPIOF
#define MX_FMC_A3_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A3_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A3_GPIO_Pin                      GPIO_PIN_3
#define MX_FMC_A3_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A3_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PF4 */
#define MX_FMC_A4_Pin                           PF4
#define MX_FMC_A4_GPIOx                         GPIOF
#define MX_FMC_A4_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A4_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A4_GPIO_Pin                      GPIO_PIN_4
#define MX_FMC_A4_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A4_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PF5 */
#define MX_FMC_A5_Pin                           PF5
#define MX_FMC_A5_GPIOx                         GPIOF
#define MX_FMC_A5_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A5_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A5_GPIO_Pin                      GPIO_PIN_5
#define MX_FMC_A5_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A5_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PG0 */
#define MX_FMC_A10_Pin                          PG0
#define MX_FMC_A10_GPIOx                        GPIOG
#define MX_FMC_A10_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A10_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A10_GPIO_Pin                     GPIO_PIN_0
#define MX_FMC_A10_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A10_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PF12 */
#define MX_FMC_A6_Pin                           PF12
#define MX_FMC_A6_GPIOx                         GPIOF
#define MX_FMC_A6_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A6_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A6_GPIO_Pin                      GPIO_PIN_12
#define MX_FMC_A6_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A6_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD9 */
#define MX_FMC_D14_DA14_Pin                     PD9
#define MX_FMC_D14_DA14_GPIOx                   GPIOD
#define MX_FMC_D14_DA14_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D14_DA14_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D14_DA14_GPIO_Pin                GPIO_PIN_9
#define MX_FMC_D14_DA14_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D14_DA14_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PF13 */
#define MX_FMC_A7_Pin                           PF13
#define MX_FMC_A7_GPIOx                         GPIOF
#define MX_FMC_A7_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A7_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A7_GPIO_Pin                      GPIO_PIN_13
#define MX_FMC_A7_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A7_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PG2 */
#define MX_FMC_A12_Pin                          PG2
#define MX_FMC_A12_GPIOx                        GPIOG
#define MX_FMC_A12_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A12_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A12_GPIO_Pin                     GPIO_PIN_2
#define MX_FMC_A12_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A12_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PF14 */
#define MX_FMC_A8_Pin                           PF14
#define MX_FMC_A8_GPIOx                         GPIOF
#define MX_FMC_A8_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A8_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A8_GPIO_Pin                      GPIO_PIN_14
#define MX_FMC_A8_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A8_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PG1 */
#define MX_FMC_A11_Pin                          PG1
#define MX_FMC_A11_GPIOx                        GPIOG
#define MX_FMC_A11_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A11_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A11_GPIO_Pin                     GPIO_PIN_1
#define MX_FMC_A11_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A11_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PF15 */
#define MX_FMC_A9_Pin                           PF15
#define MX_FMC_A9_GPIOx                         GPIOF
#define MX_FMC_A9_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A9_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A9_GPIO_Pin                      GPIO_PIN_15
#define MX_FMC_A9_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A9_GPIO_Mode                     GPIO_MODE_AF_PP

/* Pin PD5 */
#define MX_FMC_NWE_Pin                          PD5
#define MX_FMC_NWE_GPIOx                        GPIOD
#define MX_FMC_NWE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_NWE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NWE_GPIO_Pin                     GPIO_PIN_5
#define MX_FMC_NWE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NWE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PE14 */
#define MX_FMC_D11_DA11_Pin                     PE14
#define MX_FMC_D11_DA11_GPIOx                   GPIOE
#define MX_FMC_D11_DA11_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D11_DA11_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D11_DA11_GPIO_Pin                GPIO_PIN_14
#define MX_FMC_D11_DA11_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D11_DA11_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PE7 */
#define MX_FMC_D4_DA4_Pin                       PE7
#define MX_FMC_D4_DA4_GPIOx                     GPIOE
#define MX_FMC_D4_DA4_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D4_DA4_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D4_DA4_GPIO_Pin                  GPIO_PIN_7
#define MX_FMC_D4_DA4_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D4_DA4_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE10 */
#define MX_FMC_D7_DA7_Pin                       PE10
#define MX_FMC_D7_DA7_GPIOx                     GPIOE
#define MX_FMC_D7_DA7_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D7_DA7_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D7_DA7_GPIO_Pin                  GPIO_PIN_10
#define MX_FMC_D7_DA7_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D7_DA7_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD14 */
#define MX_FMC_D0_DA0_Pin                       PD14
#define MX_FMC_D0_DA0_GPIOx                     GPIOD
#define MX_FMC_D0_DA0_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D0_DA0_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D0_DA0_GPIO_Pin                  GPIO_PIN_14
#define MX_FMC_D0_DA0_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D0_DA0_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE8 */
#define MX_FMC_D5_DA5_Pin                       PE8
#define MX_FMC_D5_DA5_GPIOx                     GPIOE
#define MX_FMC_D5_DA5_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D5_DA5_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D5_DA5_GPIO_Pin                  GPIO_PIN_8
#define MX_FMC_D5_DA5_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D5_DA5_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE13 */
#define MX_FMC_D10_DA10_Pin                     PE13
#define MX_FMC_D10_DA10_GPIOx                   GPIOE
#define MX_FMC_D10_DA10_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D10_DA10_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D10_DA10_GPIO_Pin                GPIO_PIN_13
#define MX_FMC_D10_DA10_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D10_DA10_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PD8 */
#define MX_FMC_D13_DA13_Pin                     PD8
#define MX_FMC_D13_DA13_GPIOx                   GPIOD
#define MX_FMC_D13_DA13_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D13_DA13_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D13_DA13_GPIO_Pin                GPIO_PIN_8
#define MX_FMC_D13_DA13_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D13_DA13_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PE15 */
#define MX_FMC_D12_DA12_Pin                     PE15
#define MX_FMC_D12_DA12_GPIOx                   GPIOE
#define MX_FMC_D12_DA12_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D12_DA12_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D12_DA12_GPIO_Pin                GPIO_PIN_15
#define MX_FMC_D12_DA12_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D12_DA12_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PD4 */
#define MX_FMC_NOE_Pin                          PD4
#define MX_FMC_NOE_GPIOx                        GPIOD
#define MX_FMC_NOE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_NOE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NOE_GPIO_Pin                     GPIO_PIN_4
#define MX_FMC_NOE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NOE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD15 */
#define MX_FMC_D1_DA1_Pin                       PD15
#define MX_FMC_D1_DA1_GPIOx                     GPIOD
#define MX_FMC_D1_DA1_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D1_DA1_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D1_DA1_GPIO_Pin                  GPIO_PIN_15
#define MX_FMC_D1_DA1_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D1_DA1_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PG4 */
#define MX_FMC_A14_Pin                          PG4
#define MX_FMC_A14_GPIOx                        GPIOG
#define MX_FMC_A14_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A14_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A14_GPIO_Pin                     GPIO_PIN_4
#define MX_FMC_A14_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A14_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PG3 */
#define MX_FMC_A13_Pin                          PG3
#define MX_FMC_A13_GPIOx                        GPIOG
#define MX_FMC_A13_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A13_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A13_GPIO_Pin                     GPIO_PIN_3
#define MX_FMC_A13_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A13_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PG5 */
#define MX_FMC_A15_Pin                          PG5
#define MX_FMC_A15_GPIOx                        GPIOG
#define MX_FMC_A15_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A15_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A15_GPIO_Pin                     GPIO_PIN_5
#define MX_FMC_A15_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A15_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PE12 */
#define MX_FMC_D9_DA9_Pin                       PE12
#define MX_FMC_D9_DA9_GPIOx                     GPIOE
#define MX_FMC_D9_DA9_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D9_DA9_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D9_DA9_GPIO_Pin                  GPIO_PIN_12
#define MX_FMC_D9_DA9_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D9_DA9_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD0 */
#define MX_FMC_D2_DA2_Pin                       PD0
#define MX_FMC_D2_DA2_GPIOx                     GPIOD
#define MX_FMC_D2_DA2_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D2_DA2_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D2_DA2_GPIO_Pin                  GPIO_PIN_0
#define MX_FMC_D2_DA2_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D2_DA2_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE9 */
#define MX_FMC_D6_DA6_Pin                       PE9
#define MX_FMC_D6_DA6_GPIOx                     GPIOE
#define MX_FMC_D6_DA6_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D6_DA6_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D6_DA6_GPIO_Pin                  GPIO_PIN_9
#define MX_FMC_D6_DA6_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D6_DA6_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD10 */
#define MX_FMC_D15_DA15_Pin                     PD10
#define MX_FMC_D15_DA15_GPIOx                   GPIOD
#define MX_FMC_D15_DA15_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D15_DA15_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D15_DA15_GPIO_Pin                GPIO_PIN_10
#define MX_FMC_D15_DA15_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D15_DA15_GPIO_Mode               GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- USB_OTG_FS --------------------------------*/

#define MX_USB_OTG_FS                           1

#define MX_USB_OTG_FS_DEVICE                    1

/* GPIO Configuration */

/* Pin PA11 */
#define MX_USB_OTG_FS_DM_GPIO_Speed             GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DM_Pin                    PA11
#define MX_USB_OTG_FS_DM_GPIOx                  GPIOA
#define MX_USB_OTG_FS_DM_GPIO_PuPd              GPIO_NOPULL
#define MX_USB_OTG_FS_DM_GPIO_Pin               GPIO_PIN_11
#define MX_USB_OTG_FS_DM_GPIO_AF                GPIO_AF10_OTG_FS
#define MX_USB_OTG_FS_DM_GPIO_Mode              GPIO_MODE_AF_PP

/* Pin PA12 */
#define MX_USB_OTG_FS_DP_GPIO_Speed             GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USB_OTG_FS_DP_Pin                    PA12
#define MX_USB_OTG_FS_DP_GPIOx                  GPIOA
#define MX_USB_OTG_FS_DP_GPIO_PuPd              GPIO_NOPULL
#define MX_USB_OTG_FS_DP_GPIO_Pin               GPIO_PIN_12
#define MX_USB_OTG_FS_DP_GPIO_AF                GPIO_AF10_OTG_FS
#define MX_USB_OTG_FS_DP_GPIO_Mode              GPIO_MODE_AF_PP

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

